---
title: "crossfitsvis"
author: "tara"
date: "8/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(purrr)
library(ggplot2)
library(Metrics)
library(corrplot)
#library(kableExtra)
library(metR)
library(cowplot)
library(grid)
library(gridExtra)
library(ggrepel)
library(ggbreak)
library(plotly)
```



**Import parallel crossfits data**
```{r}
#the following CSVs were created on the 50 core server using the script parallelCrossfit.R. 
pxfit1 <-read.csv("crossfits_sim1.csv",header=TRUE)
pxfit2 <-read.csv("crossfits_sim2.csv",header=TRUE)
pxfit3 <-read.csv("crossfits_sim3.csv",header=TRUE)

pxfits <-pxfit1
test_length = 10
```


**Visualize parallel crossfits data: step one, organize the data**
```{r}

pxfits$age <-fct_recode(pxfits$age_class, "1"="V1","2"="V2","3"="V3","4"="V4","5"="V5","6"="V6","7"="V7","8"="V8","9"="V9","10"="V10","11"="V11","12"="V12","13"="V13","14"="V14","15"="V15","16"="V16","17"="V17","18"="V18","19"="V19","20"="V20")

pxfits <-mutate(pxfits, age=as.numeric(as.character(age)))#%>%mutate(numpoints=time_step*age, NRMSE=rmse/obs_SD)

#turn this on and off
#pxfits <-na.omit(pxfits)

###mean and standard deviation of the time series. 
pxsum <-pxfits %>%group_by(age, time_step)%>%summarize(medRSQ=median(Rsq), sdRSQ = sd(Rsq), meanRSQ=mean(Rsq), E=max(E), sdRMSE=sd(rmse), meanRMSE=mean(rmse),sdDYRHO=sd(dy_rho), meanDYRHO=mean(dy_rho),maxRSQ =max(Rsq),
                                                       #meanNRMSE=mean(NRMSE), sdNRMSE=sd(NRMSE),
                                                       .groups='drop')
```

**Contour plot in Plotly**
Format
```{r}
#what is the metric you are trying to make a plot out of?
met <-"meanRSQ"
metname <-"mean r-squared"

#max z back into a matrix
rhomat <-pivot_wider(pxsum, id_cols="time_step",names_from = "age",values_from = met)
rhomat <-rhomat %>% remove_rownames %>% mutate(time_step =time_step - test_length) %>% column_to_rownames(var="time_step") #when using the 10 year sequential
#rhomat <-rhomat %>% remove_rownames %>% column_to_rownames(var="time_step")
rhomat <-as.matrix(rhomat)
```

**contour plot**  
```{r}
z_data = t(rhomat)

contours <- list(
    showlabels = TRUE,
    start = floor(min(unlist(z_data))), #the min for sim III full data is -1.078, so lets go to -1.1, the max is 0.999758, 
    end = ceiling(max(unlist(z_data))),
    labelfont = list(size = 20, color = "black"))

#whole plot
fig1 <-plot_ly(type="contour",
               contours = list(showlabels = TRUE),
               #contours = contours,
               #colorscale='Jet',
               #coloraxis="coloraxis",
               #colorscale = list(c(-1.2,-1.0,-0.8,-0.6,-0.5,-0.4,-0.2,0,0.1,0.4,0.6,0.8,0.9,1.0)),
               #colorscale = list(seq(0.78,1.0,0.02),c("#dc2f02","#d00000","#9d0208","#6a040f","#370617","#03071e")),
               colorbar=list(tickfont=list(size=14)),
               reversescale =F,
               autocontour = F, #contours = list(start = -1.2, end = 1.0,size = 0.2),
               x=~rownames(rhomat), y=~colnames(rhomat), z=~t(rhomat))%>%
      colorbar(title=metname, size=14)%>%
      layout(xaxis = list(title = 'years included',tickfont = list(size = 14),titlefont = list(size = 14),
                          #nticks=25,range=c(5,30)),
                          nticks=10),
                                     yaxis = list(title = 'number age classes included',
                                                  tickfont = list(size = 14),titlefont = list(size = 14)),
                                     zaxis = list(title = 'r-squared',nticks=10, range=c(0,1),tickfont = list(size = 14)))
                                    # zaxis = list(title = metname))   
fig1
```

**Zoom in on contour plot**
```{r}
#zooming in
rhomat2 <-rhomat[1:11,] #5-15  
#rhomat2 <-rhomat[6:11,1:10] #10-15 years, 1-10 ages  
#rhomat <-rhomat[11:16,1:10] #11-16 years, 1-10 ages  #for the 2 spp med



#zoom in 
fig2 <-plot_ly(type="contour",
               contours = list(showlabels = TRUE),
               #contours = contours,
               colorscale='Jet',
               #colorscale = list(seq(0.78,1.0,0.02),c("#dc2f02","#d00000","#9d0208","#6a040f","#370617","#03071e")),
               #coloraxis="coloraxis",
               colorbar=list(tickfont=list(size=14)),
               reversescale =F,
               autocontour = F, #contours = list(start = -1.2, end = 1.0,size = 0.2),
               x=~rownames(rhomat2), y=~colnames(rhomat2), z=~t(rhomat2))%>%
      colorbar(title=metname, size=14)%>%
      layout(xaxis = list(title = 'years included',
                          tickfont = list(size = 14), titlefont = list(size = 14),
                          nticks=10),
                                     yaxis = list(title = 'number age classes included',
                                                  tickfont = list(size = 14),titlefont = list(size = 14)),
                                     zaxis = list(title = 'r-squared',nticks=10, range=c(0,1)))
                                    # zaxis = list(title = metname))   
 
#fig <- subplot(fig1, fig2)
#fig <- fig %>% layout(coloraxis=list(colorscale='Jet'))



fig2
```

##### MESSING AROUND ######

**surface plot**
```{r}
#As surface plot
#fig <-plot_ly(type="surface",
             # x=~rownames(rhomat), y=~colnames(rhomat), z=~t(rhomat))
#fig %>% layout(scene = list(xaxis = list(title = 'years included', nticks=8, range=c(5,40)),
                                     #yaxis = list(title = 'number age classes included', nticks=10, range=c(1,20)),
                                     #zaxis = list(title = 'r-squared',nticks=10, range=c(0,1)))) 
                                     #zaxis = list(title = metname)))
                                     #
#calc r-squared range
``` 





**mean dynamic correlation in plotly**
```{r}
#what is the metric you are trying to make a plot out of?
met <-"meanDYRHO"
metname <-"mean dynamic correlation"

#max z back into a matrix
rhomat <-pivot_wider(pxsum, id_cols="time_step",names_from = "age",values_from = met)
rhomat <-rhomat %>% remove_rownames %>% mutate(time_step =time_step - 10) %>% column_to_rownames(var="time_step") #when using the 10 year sequential
#rhomat <-rhomat %>% remove_rownames %>% column_to_rownames(var="time_step")
rhomat <-as.matrix(rhomat)

#As surface plot
#fig <-plot_ly(type="surface",
             # x=~rownames(rhomat), y=~colnames(rhomat), z=~t(rhomat))
#fig %>% layout(scene = list(xaxis = list(title = 'years included', nticks=8, range=c(5,40)),
                                     #yaxis = list(title = 'number age classes included', nticks=10, range=c(1,20)),
                                     #zaxis = list(title = 'r-squared',nticks=10, range=c(0,1)))) 
                                     #zaxis = list(title = metname)))
                                     #
#calc r-squared range
 

#zooming in
#rhomat <-rhomat[1:11,] #5-15     
#rhomat <-rhomat[6:11,1:10] #10-15 years, 1-10 ages  

#as contour plot
#https://community.plotly.com/t/what-colorscales-are-available-in-plotly-and-which-are-the-default/2079
#https://stackoverflow.com/questions/55164195/how-to-manually-set-the-color-scale-in-contour-plots-r-plotly
fig2 <-plot_ly(type="contour",contours = list(showlabels = TRUE),
               #colorscale='Picnic',
               colorscale = list(c(0, 0.5, 1), c('blue', 'yellow', 'red')),
               reversescale =F,
               autocontour = F, contours = list(start = 0, end = 1.0,size = 0.5),
               x=~rownames(rhomat), y=~colnames(rhomat), z=~t(rhomat))%>%
      colorbar(title=metname)%>%
      layout(xaxis = list(title = 'years included',
                          #nticks=25,range=c(5,30)),
                          nticks=10),
                                     yaxis = list(title = 'number age classes included'),
                                     #zaxis = list(title = 'r-squared',nticks=10, range=c(0,1)))) 
                                     zaxis = list(title = metname))   
fig2   

```


**Contour in ggplot**
```{r}

#ZOOM IN 
#pxsum <-filter(pxsum, time_step <= 25 & time_step >=20 & age <=10)
#pxsum2 <-pxsum

#yet another way to do contour plots (in ggplot)
rsqcont <-dplyr::select(pxsum, age, time_step, meanRSQ)%>%mutate(time_step=time_step-10)%>%as.data.frame
rsqcont %>%
  ggplot(aes(x=time_step,y=age,z=meanRSQ))+
  #geom_density2d_filled()
  geom_contour_filled()+
  #geom_tile(color="white", fill="white")+
  #scale_color_manual(labels = c("T999", "T888"), values = c("blue", "red")) +
  #geom_contour()+
  scale_x_continuous(breaks=seq(min(rsqcont$time_step), max(rsqcont$time_step),1))+
  scale_y_continuous(breaks=seq(min(rsqcont$age),max(rsqcont$age),1))+
  #xlim(5,30)+
  #geom_text_contour(aes(z = round(meanRSQ,2)), check_overlap = TRUE)+
  xlab("number of years included")+ylab("age classes included")+
  #scale_x_discrete(limits=c(as.character(seq(5,30,1))))+
  theme_classic()
```

**as a tile plot**
```{r}
cols <- c("(-1.2,-1.0]"="white","(-1.0,-0.8]"="#f1eef6", "(-0.6,-0.4]" = "#d0d1e6", "(-0.4,-0.2]" = "#a6bddb", "(-0.2,0]" = "#74a9cf", "(0,0.2]"  = "#2b8cbe", "(0.2,0.4]"="#045a8d", "(0.4,0.6]" ="#034e7b", "(0.6,0.8]" ="#011f4b","(0.8,1.0]" ="black")

#p <- separate(p, contrast, c("bayyear1", "bayyear2"),sep="-")
#p<-mutate(p, p_if_sig=ifelse(sigp=="sig",p.value,NA), starsig=ifelse(sigp=="sig","*",NA)) 
pxsum3<-mutate(pxsum, meanRSQcut = cut(meanRSQ, breaks=seq(-1.2,1,0.2)))
ggplot(pxsum3, aes(age,time_step))+
  geom_tile(aes(fill=meanRSQ), show.legend = TRUE)+
  scale_fill_viridis_c()+coord_flip()+
  #scale_fill_manual(values=cols)+
  #geom_text(color="white", size=3)+
  xlab("")+ylab("")+
  theme(axis.text.x = element_text(angle = 90),panel.background = element_rect(fill = "white", colour = "black"))

```


**As a table**
```{r}
round(rhomat,3) %>% kbl()%>%kable_classic(full_width = T, html_font = "Cambria")

```

**zoom in on the contour plot for 10 years: PLOTLY**
```{r}
#ZOOM IN ON THE CONTOUR PLOT
pxsum_clip <-filter(pxsum, time_step <= 10)

#what is the metric you are trying to make a plot out of?
met <-"meanRSQ"
metname <-"mean R-squared"
  
#max z back into a matrix
rhomat <-pivot_wider(pxsum_clip, id_cols="time_step",names_from = "age",values_from = met)
rhomat <-rhomat %>% remove_rownames %>% column_to_rownames(var="time_step")
rhomat <-as.matrix(rhomat)

#as contour plot
fig2 <-plot_ly(type="contour",contours = list(showlabels = TRUE),
               colorscale='Jet',reversescale =T,
               autocontour = F, contours = list(start = -1.2, end = 1.0,size = 0.2),
               x=~rownames(rhomat), y=~colnames(rhomat), z=~t(rhomat))%>%
      colorbar(title=metname)%>%
      layout(xaxis = list(title = 'years included'),
                                     yaxis = list(title = 'number age classes included'),
                                     #zaxis = list(title = 'r-squared',nticks=10, range=c(0,1)))) 
                                     zaxis = list(title = metname))   
fig2  
```


**Dynamic correlation**
```{r}
#preylist <-read.csv("preylists2sppXXL.csv",header=T)%>%filter(index==1)%>%dplyr::select(-X, -recnoise1,-recnoise2)
preylist <-read.csv("preylists2sppMED.csv",header=T)%>%filter(index==1)%>%dplyr::select(-X, -recnoise1,-recnoise2)
#preylist <-read.csv("preylistsOneSpp.csv",header=T)%>%filter(index==1)%>%dplyr::select(-X, -recnoise1,-recnoise2)

# scaling the data doesn't seem to change the output 
blockpiv <-filter(preylist, time_step >299 & time_step <=400)
maxE <-round(sqrt(100))
vars = unique(blockpiv$age_class)
var_pairs = combn(vars, 2) # Combinations of vars, 2 at a time
rho_matrix2spp = array(NA, dim = c(length(vars), length(vars)), dimnames = list(vars,vars)) 
for (i in 1:ncol(var_pairs)) {
  df = filter(blockpiv, age_class %in% c(var_pairs[1,i], var_pairs[2,i]))
  fitSB <-fitGP(data = df, yd = "value", pop="age_class",scaling = "local", E=maxE, tau=1, predictmethod = "loo")
  fitSB_rho <-tail(fitSB$pars,1)
  rho_matrix2spp[var_pairs[1,i], var_pairs[2,i]] = fitSB_rho
}

corrplot(rho_matrix2spp, method="color", type="upper", diag=FALSE, is.corr = TRUE)

blockpiv%>%
  ggplot(aes(time_step, value))+
  geom_line()+facet_wrap(~age_class)+theme_classic()



```
